# Generated by Django 6.0.6 on 2026-07-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('community_health', 'Community Health'), ('documentation', 'Documentation'), ('contributing', 'Contributing'), ('issue_templates', 'Issue Templates'), ('pr_templates', 'Pull Request Templates'), ('github_config', 'GitHub Configuration'), ('issue_forms', 'GitHub Issue Forms'), ('discussions', 'GitHub Discussions')], default='documentation', max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
